name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "cldb"
database_id = "b990dd27-6d61-469d-acdb-c5571e82ccb3"

[[kv_namespaces]]
binding = "kv"
id = "c2b0b3983dc44f6f9136dbe01eaf8d26"

#[[r2_buckets]]
#binding = "r2"
#bucket_name = ""

#[[send_email]]
#name = "email"

[ai]
binding = "ai"

[assets]
binding = "assets"
directory = "mail-vue"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 * * * *"]

[vars]
domain = ["xxbeimc.de5.net"]
admin = "LemonXStudio@xxbeimc.de5.net"
jwt_secret = "xxbeimc9396"

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
